### ISSUE TITLE
How I Hacked computrabajo.com

### ISSUE THREAD

**Issue by joshuamarquez** [andersonDadario/howihacked#1]
I've written about this in http://joshuamarquez.me/2016/06/29/how-i-hacked-computrabajo/

**Comment by andersonDadario** [comment]
Hey @joshuamarquez 

Thanks for your interest in contributing.

Before I add that to the website, may I ask you whether you have their consent to publish how you hacked if they didn't fix the vulnerability yet? If yes, could you share such authorization with me?

Best

**Comment by andersonDadario** [comment]
It seems that there is no answer. Closing issue.
